# 文件名config.yaml
- download:
   mode: 0
   url: http://192.168.23.14/工具/nmap
#- download:
#   mode: 1
#   url: http://192.168.23.14/svn/工具/nmap
- test:
   type: security
   subtype: nmap
   ip: 127.0.0.1
   port: 80-89
   arguments: -Pn -sS -A
#- test:
#   type: security
#   subtype: nmap
#   ip: 127.0.0.1
#   port: 80-89
#   arguments: -Pn

